{% set name = "mlo-co2" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlo_co2-{{ version }}.tar.gz
  sha256: a06bcac8800f44dbb57183fa9e79e5101974d986de6d9422a2769919efab0455

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - mlo_co2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kylepollina/mlo_co2
  summary: Scrape CO2 data from Mauna Loa Observatory off of NOAA Earth Science Research Lab
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
